- name: Install Kubernetes Master
  hosts: Master_Node
  become: true
  roles:
    - kubernetes-master

- name: Install Kubernetes Worker
  hosts: Worker_Node
  become: true
  roles:
    - kubernetes-worker