- name: Install Kubernetes Master
  hosts: Master_Node
  remote_user: ubuntu
  roles:
    - kubernetes-master

- name: Install Kubernetes Worker
  hosts: Worker_Node
  become: true
  roles:
    - kubernetes-worker

- name: Deploy WebGoat and other utilities
  hosts: Master_Node
  become: true
  remote_user: ubuntu
  roles:
    - kubernetes-master-deploy