- name: Copy k8s manifest to master node
  copy:
    src: deployment.yml
    dest: "/tmp/kubernetes_manifests"
    remote_src: yes

- name: Deploy web app on worker node
  shell: "sudo kubectl apply -f /tmp/kubernetes_manifests"
  become_user: root