- name: Disabling Swap on all nodes
  become: true
  shell: swapoff -a

- name: Commenting Swap entries in /etc/fstab
  become: true
  replace:
      path: /etc/fstab
      regexp: "(^/.*swap*)"
      replace: '# \1'

- name: Install Docker
  become: true
  apt:
      name: docker.io
      state: present

- name: Add Kubernetes APT key
  become: true
  apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

- name: Add Kubernetes APT repo
  become: true
  apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present

- name: Install kubeadm, kubelet, kubectl and iproute-tc
  become: true
  apt:
      name: "{{ item }}"
      state: present
  loop:
      - kubeadm
      - kubelet
      - kubectl
      - iproute-tc

- name: Generate join token
  shell: kubeadm token create --print-join-command
  register: kubeadm_join_cmd
  delegate_to: "{{ groups['Master_Node'][0] }}"

- set_fact:
      kubeadm_join: "{{ kubeadm_join_cmd.stdout }}"

- debug: var=kubeadm_join

- name: Store join command
  action: copy content="{{ kubeadm_join }}" dest="/etc/kubernetes/kubeadm-join.command"

- name: Run kubeadm join
  shell: "{{ kubeadm_join }} --ignore-preflight-errors=swap"
